# Site settings
title: Power Platform Governance Framework
author :
  name : Nicolas Kirrmann
description : "A set of best practice to master the governance of Power Platform in your organization !"

# Build settings
theme: jekyll/minima
